service:
- docker

env:
  global:
  - TERM=dumb
  - secure: NK7OCMx8aAKpa60p3kWItgi9PCrCtNseACE1bvcTjFtMq18H9j8hEtEsfCgATNdBVMExMQd0tlQPG4HIR2Xn31EQnobjf5TYbCSjZE0WNMp6kpjcBn6iq8gL27qlx+w8JmmZsIGaaSSXoTubHPWzqXuNLrEuGHp15ZjVQzgUrsnbpFFxv3kOteXlY0ICdLJdLt3o7YEEOw3Bt4/4/AlQYafTxCaiv6qOk93YQTbXhiooky3Do1cULnjN7exVVsTZk42WXIXWxUuAYJay9DsJtmsAWa90NbNfyM6Vmg0swIQVGBZpl72YnVcQN1+SMKlX9r1IszLo3RAJTCmJRTv3/kjQKh7aY6Uf2qI5xdnpG5kewRLTGJrabQqqmdEhSL02tHlKOSMrUu1I4R9zlQa40FsV4m97bpbgGEgRogMUjB74d4xP2BYktM+JeaEoQQ4sKxQ9pYfDOjYZH8siTZK5kscLYZoUm3E4aSCNJiWqMVuOMxnH3L9wPX8XDXFhwsjeVOlz8c1eV0ZoCD7FMCS0LrcOk9Dv//y1lzMwK93wYUyDqNxH+w6gWkoXa+Ba7uq2SYJwPQqQJ8cLuI8z3ovSBkUdv6AtySdkxwAia42Jb/0WC07sp0EZ53F/7ObYvAwe2o5KHzjAnv1IaYniSMea7wsd8Gxk9CxFv5+3hnALvtM=

language: java
jdk: oraclejdk8

addons:
  apt:
    update: true
    packages:
    - sudo
    - lsof
    - bash
    - unzip
    - curl
    - jq
    - libxml2-utils
    - docker-ce
    - python-pip

install: true
before_script:
- sudo pip install docker-compose httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 80

script:
- bash gradlew >/dev/null
- java -jar ./build/libs/*.jar &
- wait_for 8080
- http :8080
- stop_any 8080 80
#
- bash ./build/libs/*.jar &
- wait_for 8080
- http :8080
- stop_any 8080 80
#
- bash gradlew composeUp
- http :8080
- bash gradlew composeDown
#
- bash mvnw >/dev/null
- java -jar ./target/*.jar &
- wait_for 8080
- http :8080
- stop_any 8080 80
#
- bash ./target/*.jar &
- wait_for 8080
- http :8080
- stop_any 8080 80
#
- bash mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:up -P docker
- sleep 20
- http :8080
- bash mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:down -P docker

before_deploy: ./gradlew documentation

deploy:
  provider: pages
  skip-cleanup: true
  # travis encrypt GITHUB_TOKEN=<your github repo token> --add
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: target/generated-docs
  target_branch: gh-pages

before_cache:
- bash -c 'for item in $(find ~/.gradle -name "*.lock"); do sudo rm -rf $item ; done'

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - $HOME/.docker
